name: Build and Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Init build folder
      run: |
        cmake -S . -B build
    - name: Build
      run: |
        cmake --build build
      